version: '3'

services:
  springboot-docker-compose-app-container:
    build: .
    ports:
      - "80:5000"
    depends_on:
    - friendservice
    volumes:
    - .:/code
    networks:
    - mynet
  friendservice:
    build: ./Pirmas
    command: python app.py
    volumes:
    - ./Pirmas:/code
    ports:
    - 5000:5001
    networks:
    - mynet
    
networks:
    mynet: